#include "capsule/generator.h"
#include "capsule/hashing.h"
#include "capsule/parser.h"
#include "testing/testing.h"

using ::testing::IsOk;

namespace {

TEST(GeneratorFullFeatureTest) {
  std::string_view input_schema = R"(
        namespace test_ns

        capsule SubCapsule {
            u32 sub_id
        }

        capsule FullFeature {
            u32 id
            u16 code
            bool enabled
            string name
            vector<string> items
            SubCapsule nested

            @default(42)
            @former_name(legacy_count)
            u32 count

            @retired
            u32 old_field
        }
    )";

  capsule::Parser parser(input_schema, "full_feature.capsule");
  auto parse_result = parser.Parse();
  ASSERT_THAT(parse_result.result(), IsOk());

  capsule::CapsuleFile cf = std::move(parse_result.ValueOrDie());
  ASSERT_THAT(capsule::ComputeAndValidateHashes(&cf), IsOk());

  auto gen_result = capsule::GenerateHeader(cf);
  ASSERT_THAT(gen_result.result(), IsOk());

  std::string expected =
      "// Generated by Capsule Compiler\n"
      "#pragma once\n"
      "\n"
      "#include <cstdint>\n"
      "#include <string>\n"
      "#include <vector>\n"
      "#include \"capsule/decoder.h\"\n"
      "#include \"capsule/encoder.h\"\n"
      "#include \"capsule/size_builder.h\"\n"
      "#include \"capsule/storage.h\"\n"
      "#include \"core/vocabulary.h\"\n"
      "\n"
      "namespace test_ns {\n"
      "\n"
      "struct SubCapsuleM;\n"
      "struct SubCapsuleV;\n"
      "struct FullFeatureM;\n"
      "struct FullFeatureV;\n"
      "\n"
      "struct SubCapsuleBase {\n"
      "  using MaterializedType = SubCapsuleM;\n"
      "  using ViewType = SubCapsuleV;\n"
      "\n"
      "  static constexpr uint32_t kFieldCount = 1;\n"
      "  static constexpr ::core::CRC32C sub_id_FieldHash = "
      "::core::CRC32C(0xc3111098u);\n"
      "  static constexpr uint32_t sub_id_Default = 0;\n"
      "  static constexpr int sub_id_Index = 0;\n"
      "\n"
      "  bool has_sub_id() const { return has_[sub_id_Index]; }\n"
      "\n"
      "  std::vector<bool> has_;\n"
      "};\n"
      "\n"
      "struct FullFeatureBase {\n"
      "  using MaterializedType = FullFeatureM;\n"
      "  using ViewType = FullFeatureV;\n"
      "\n"
      "  static constexpr uint32_t kFieldCount = 8;\n"
      "  static constexpr ::core::CRC32C id_FieldHash = "
      "::core::CRC32C(0x59170d66u);\n"
      "  static constexpr ::core::CRC32C code_FieldHash = "
      "::core::CRC32C(0xa6676b57u);\n"
      "  static constexpr ::core::CRC32C enabled_FieldHash = "
      "::core::CRC32C(0x9ff42404u);\n"
      "  static constexpr ::core::CRC32C name_FieldHash = "
      "::core::CRC32C(0x911200e7u);\n"
      "  static constexpr ::core::CRC32C items_FieldHash = "
      "::core::CRC32C(0x45eef316u);\n"
      "  static constexpr ::core::CRC32C nested_FieldHash = "
      "::core::CRC32C(0x6578b947u);\n"
      "  static constexpr ::core::CRC32C count_FieldHash = "
      "::core::CRC32C(0x1d26cdc5u);\n"
      "  static constexpr ::core::CRC32C old_field_FieldHash = "
      "::core::CRC32C(0x42b25ee5u);\n"
      "  static constexpr uint32_t id_Default = 0;\n"
      "  static constexpr uint16_t code_Default = 0;\n"
      "  static constexpr std::string name_Default = \"\";\n"
      "  static constexpr uint32_t count_Default = 42;\n"
      "  static constexpr uint32_t old_field_Default = 0;\n"
      "  static constexpr int id_Index = 0;\n"
      "  static constexpr int code_Index = 1;\n"
      "  static constexpr int enabled_Index = 2;\n"
      "  static constexpr int name_Index = 3;\n"
      "  static constexpr int items_Index = 4;\n"
      "  static constexpr int nested_Index = 5;\n"
      "  static constexpr int count_Index = 6;\n"
      "  static constexpr int old_field_Index = 7;\n"
      "\n"
      "  bool has_id() const { return has_[id_Index]; }\n"
      "  bool has_code() const { return has_[code_Index]; }\n"
      "  bool has_enabled() const { return has_[enabled_Index]; }\n"
      "  bool has_name() const { return has_[name_Index]; }\n"
      "  bool has_items() const { return has_[items_Index]; }\n"
      "  bool has_nested() const { return has_[nested_Index]; }\n"
      "  bool has_count() const { return has_[count_Index]; }\n"
      "  bool has_old_field() const { return has_[old_field_Index]; }\n"
      "\n"
      "  std::vector<bool> has_;\n"
      "};\n"
      "\n"
      "struct SubCapsule {\n"
      "  uint32_t sub_id;\n"
      "};\n"
      "\n"
      "struct FullFeature {\n"
      "  uint32_t id;\n"
      "  uint16_t code;\n"
      "  bool enabled;\n"
      "  std::string name;\n"
      "  std::vector<std::string> items;\n"
      "  SubCapsule nested;\n"
      "  uint32_t count;\n"
      "  uint32_t old_field;\n"
      "};\n"
      "\n"
      "}  // namespace test_ns\n";

  EXPECT_EQ(gen_result.ValueOrDie(), expected);
}

}  // namespace
