#include "capsule/generator.h"
#include "capsule/parser.h"
#include "testing/testing.h"

TEST(GeneratorFullFeatureTest) {
  std::string_view input_schema = R"(
        namespace test_ns

        capsule SubCapsule {
            u32 sub_id
        }

        capsule FullFeature {
            u32 id
            u16 code
            bool enabled
            string name
            vector<string> items
            SubCapsule nested

            @default(42)
            @former_name("legacy_count")
            u32 count

            @retired
            u32 old_field
        }
    )";

  capsule::Parser parser(input_schema, "full_feature.capsule");
  auto parse_result = parser.Parse();
  ASSERT_TRUE(parse_result.ok());

  auto gen_result = capsule::GenerateHeader(parse_result.ValueOrDie());
  ASSERT_TRUE(gen_result.ok());

  std::string expected =
      "// Generated by Capsule Compiler\n"
      "#pragma once\n\n"
      "#include <cstdint>\n"
      "#include <string>\n"
      "#include <vector>\n"
      "#include \"capsule/decoder.h\"\n"
      "#include \"capsule/encoder.h\"\n"
      "#include \"capsule/size_builder.h\"\n"
      "#include \"capsule/storage.h\"\n"
      "#include \"core/vocabulary.h\"\n\n"
      "namespace test_ns {\n\n"
      "struct SubCapsule {\n"
      "  uint32_t sub_id;\n"
      "};\n\n"
      "struct FullFeature {\n"
      "  uint32_t id;\n"
      "  uint16_t code;\n"
      "  bool enabled;\n"
      "  std::string name;\n"
      "  std::vector<std::string> items;\n"
      "  SubCapsule nested;\n"
      "  uint32_t count;\n"
      "  uint32_t old_field;\n"
      "};\n\n"
      "}  // namespace test_ns\n";

  EXPECT_EQ(gen_result.ValueOrDie(), expected);
}
