#include <sstream>

#include "capsule/generator.h"

namespace capsule {
namespace {

std::string MapType(const std::string& tp) {
  if (tp == "u32") return "uint32_t";
  if (tp == "u16") return "uint16_t";
  if (tp == "bool") return "bool";
  if (tp == "string") return "std::string";
  if (tp.rfind("vector<", 0) == 0) {
    std::string inner = tp.substr(7, tp.size() - 8);
    return "std::vector<" + MapType(inner) + ">";
  }
  return tp;
}

}  // namespace

ResultOr<std::string> GenerateCppHeader(const CapsuleFile& file) {
  std::ostringstream oss;
  oss << "// Generated by Capsule Compiler - C++26\n";
  oss << "#pragma once\n\n";
  oss << "#include <cstdint>\n";
  oss << "#include <string>\n";
  oss << "#include <vector>\n";
  oss << "#include \"core/vocabulary.h\"\n\n";
  oss << "namespace " << file.namespace_name << " {\n\n";

  for (const auto& cp : file.capsules) {
    oss << "struct " << cp.name << " {\n";
    for (const auto& fd : cp.fields) {
      oss << "    " << MapType(fd.type) << " " << fd.name << ";\n";
    }
    oss << "};\n\n";
  }

  oss << "}  // namespace " << file.namespace_name << "\n";
  return oss.str();
}

}  // namespace capsule
