#include <sstream>

#include "capsule/generator.h"

namespace capsule {
namespace {

std::string MapType(const std::string& tp) {
  if (tp == "u64") return "uint64_t";
  if (tp == "u32") return "uint32_t";
  if (tp == "u16") return "uint16_t";
  if (tp == "u8") return "uint8_t";
  if (tp == "i64") return "int64_t";
  if (tp == "i32") return "int32_t";
  if (tp == "i16") return "int16_t";
  if (tp == "i8") return "int8_t";
  if (tp == "f64") return "double";
  if (tp == "f32") return "float";
  if (tp == "bool") return "bool";
  if (tp == "string") return "std::string";
  if (tp.rfind("vector<", 0) == 0) {
    std::string inner = tp.substr(7, tp.size() - 8);
    return "std::vector<" + MapType(inner) + ">";
  }
  return tp;
}

std::string TypeToViewType(const std::string& tp) {
  if (tp == "u64") return "uint64_t";
  if (tp == "u32") return "uint32_t";
  if (tp == "u16") return "uint16_t";
  if (tp == "u8") return "uint8_t";
  if (tp == "i64") return "int64_t";
  if (tp == "i32") return "int32_t";
  if (tp == "i16") return "int16_t";
  if (tp == "i8") return "int8_t";
  if (tp == "f64") return "double";
  if (tp == "f32") return "float";
  if (tp == "bool") return "bool";
  if (tp == "string") return "std::string_view";
  if (tp.rfind("vector<string>", 0) == 0) {
    return "std::vector<std::string_view>";
  }
  if (tp.rfind("vector<", 0) == 0) {
    std::string inner = tp.substr(7, tp.size() - 8);
    return "std::vector<" + MapType(inner) + ">";
  }
  return tp;
}

std::string CppDefaultForType(const std::string& tp) {
  if (tp == "bool") return "false";
  if (tp == "string") return "";
  if (tp == "f64") return "0.0";
  if (tp == "f32") return "0.0";
  return "0";
}

std::string CppDefaultValue(const Field& f) {
  std::string d;
  for (const auto& a : f.attributes) {
    // TODO - validate that attributes are uniquely specified
    if (a.name != "default") continue;
    d = a.value;
  }
  if (d.empty()) d = CppDefaultForType(f.type);
  if (f.type == "string") {
    d = "\"" + d + "\"";
  }
  return d;
}

bool IsVectorType(const std::string& tp) { return tp.rfind("vector<", 0) == 0; }
bool IsCapsuleType(const std::string& tp) { return MapType(tp) == tp; }

bool HasDefaultValue(const Field& f) {
  return !IsVectorType(f.type) && !IsCapsuleType(f.type);
}

bool RefsStorage(const Capsule& c) {
  for (const auto& f : c.fields) {
    if (f.type == "string" || f.type == "vector<string>") return true;
  }
  return false;
}

}  // namespace

ResultOr<std::string> GenerateHeader(const CapsuleFile& file) {
  std::ostringstream oss;
  oss << "// Generated by Capsule Compiler\n";
  oss << "#pragma once\n\n";
  oss << "#include <cstdint>\n";
  oss << "#include <memory>\n";
  oss << "#include <string>\n";
  oss << "#include <vector>\n";
  oss << "#include \"capsule/decoder.h\"\n";
  oss << "#include \"capsule/encoder.h\"\n";
  oss << "#include \"capsule/size_builder.h\"\n";
  oss << "#include \"capsule/storage.h\"\n";
  oss << "#include \"core/vocabulary.h\"\n\n";
  oss << "namespace " << file.namespace_name << " {\n\n";

  // Struct forward declarations.
  // TODO -- validate name uniqueness, including after appending M and V and
  // Base.
  for (const auto& cp : file.capsules) {
    oss << "struct " << cp.name << "M;\n";
    oss << "struct " << cp.name << "V;\n";
  }
  oss << "\n";

  // Struct base classes.
  for (const auto& cp : file.capsules) {
    oss << "struct " << cp.name << "Base {\n";
    oss << "  using MaterializedType = " << cp.name << "M;\n";
    oss << "  using ViewType = " << cp.name << "V;\n";
    oss << "\n";
    // TODO - validate fields > 0
    oss << "  static constexpr uint32_t kFieldCount = " << cp.fields.size()
        << ";\n";

    // Field hashes.
    // TODO - validate that fields will not have name collisios when names
    //        have _FieldHash, _Default, and _Index appended.
    for (int i = 0; i < cp.fields.size(); ++i) {
      const auto& f = cp.fields[i];
      if (cp.fields[i].hashes.empty()) {
        return Result(Code::kInvalidArgument,
                      strings::Format("Field {} missing hashes.", f.name));
      }
      // TODO - support hashes from former name attributes.
      oss << "  static constexpr ::core::CRC32C " << f.name
          << "_FieldHash = ::core::CRC32C(0x" << std::hex << f.hashes[0].value()
          << "u);\n";
    }

    // Field defaults.
    for (int i = 0; i < cp.fields.size(); ++i) {
      const auto& f = cp.fields[i];
      if (!HasDefaultValue(f)) continue;
      oss << "  static constexpr " << MapType(f.type) << " " << f.name
          << "_Default = " << CppDefaultValue(f) << ";\n";
    }

    // Field indexes.
    for (int i = 0; i < cp.fields.size(); ++i) {
      const auto& f = cp.fields[i];
      oss << "  static constexpr int " << f.name << "_Index = " << i << ";\n";
    }

    oss << "\n";

    // The ever-lovely has_ family of accessors.
    for (int i = 0; i < cp.fields.size(); ++i) {
      const auto& f = cp.fields[i];
      oss << "  bool has_" << f.name << "() const { return has_[" << f.name
          << "_Index]; }\n";
    }

    oss << "\n";
    oss << "  std::vector<bool> has_;\n";

    oss << "};\n";
    oss << "\n";
  }

  // Materialized structs.
  for (const auto& cp : file.capsules) {
    oss << "struct " << cp.name << "M : public " << cp.name << "Base {\n";
    for (const auto& fd : cp.fields) {
      oss << "  " << MapType(fd.type) << " " << fd.name << ";\n";
    }
    oss << "\n";
    oss << "  size_t ComputeStorageSize() const;\n";
    oss << "  void Encode(::capsule::Encoder* e) const;\n";
    oss << "  ::core::Result Decode(::capsule::Decoder* d);\n";
    oss << "};\n\n";
  }

  // View structs.
  for (const auto& cp : file.capsules) {
    oss << "struct " << cp.name << "V : public " << cp.name << "Base {\n";
    for (const auto& fd : cp.fields) {
      oss << "  " << TypeToViewType(fd.type) << " " << fd.name << ";\n";
    }
    oss << "\n";
    if (RefsStorage(cp)) {
      oss << "  std::shared_ptr<::capsule::Storage> ref_;\n\n";
    }
    oss << "  ::core::Result Decode(::capsule::Decoder* d);\n";
    oss << "  void RefIfNeeded(std::shared_ptr<::capsule::Storage> s);\n";
    oss << "};\n\n";
  }

  oss << "}  // namespace " << file.namespace_name << "\n";
  return oss.str();
}

ResultOr<std::string> GenerateSource(const CapsuleFile& file,
                                     std::string_view header_location) {
  std::ostringstream oss;
  oss << "// Generated by Capsule Compiler\n";
  oss << "#include \"" << header_location << "\"\n";
  oss << "\n";
  oss << "namespace " << file.namespace_name << " {\n\n";

  oss << "}  // namespace " << file.namespace_name << "\n";
  return oss.str();
}

}  // namespace capsule
