// Generated by Capsule Compiler
#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include "capsule/decoder.h"
#include "capsule/encoder.h"
#include "capsule/size_builder.h"
#include "capsule/storage.h"
#include "core/vocabulary.h"

namespace test_ns {

struct SubCapsuleM;
struct SubCapsuleV;
struct FullFeatureM;
struct FullFeatureV;

struct SubCapsuleBase {
  using MaterializedType = SubCapsuleM;
  using ViewType = SubCapsuleV;

  static constexpr uint32_t kFieldCount = 1;
  static constexpr ::core::CRC32C sub_id_FieldHash = ::core::CRC32C(0xc3111098u);
  static constexpr uint32_t sub_id_Default = 0;
  static constexpr int sub_id_Index = 0;

  bool has_sub_id() const { return has_[sub_id_Index]; }

  std::vector<bool> has_;
};

struct FullFeatureBase {
  using MaterializedType = FullFeatureM;
  using ViewType = FullFeatureV;

  static constexpr uint32_t kFieldCount = 8;
  static constexpr ::core::CRC32C id_FieldHash = ::core::CRC32C(0x59170d66u);
  static constexpr ::core::CRC32C code_FieldHash = ::core::CRC32C(0xa6676b57u);
  static constexpr ::core::CRC32C enabled_FieldHash = ::core::CRC32C(0x9ff42404u);
  static constexpr ::core::CRC32C name_FieldHash = ::core::CRC32C(0x911200e7u);
  static constexpr ::core::CRC32C items_FieldHash = ::core::CRC32C(0x45eef316u);
  static constexpr ::core::CRC32C nested_FieldHash = ::core::CRC32C(0x6578b947u);
  static constexpr ::core::CRC32C count_FieldHash = ::core::CRC32C(0x1d26cdc5u);
  static constexpr ::core::CRC32C old_field_FieldHash = ::core::CRC32C(0x42b25ee5u);
  static constexpr uint32_t id_Default = 0;
  static constexpr uint16_t code_Default = 0;
  static constexpr std::string name_Default = "";
  static constexpr uint32_t count_Default = 42;
  static constexpr uint32_t old_field_Default = 0;
  static constexpr int id_Index = 0;
  static constexpr int code_Index = 1;
  static constexpr int enabled_Index = 2;
  static constexpr int name_Index = 3;
  static constexpr int items_Index = 4;
  static constexpr int nested_Index = 5;
  static constexpr int count_Index = 6;
  static constexpr int old_field_Index = 7;

  bool has_id() const { return has_[id_Index]; }
  bool has_code() const { return has_[code_Index]; }
  bool has_enabled() const { return has_[enabled_Index]; }
  bool has_name() const { return has_[name_Index]; }
  bool has_items() const { return has_[items_Index]; }
  bool has_nested() const { return has_[nested_Index]; }
  bool has_count() const { return has_[count_Index]; }
  bool has_old_field() const { return has_[old_field_Index]; }

  std::vector<bool> has_;
};

struct SubCapsule {
  uint32_t sub_id;
};

struct FullFeature {
  uint32_t id;
  uint16_t code;
  bool enabled;
  std::string name;
  std::vector<std::string> items;
  SubCapsule nested;
  uint32_t count;
  uint32_t old_field;
};

}  // namespace test_ns
