// Generated by Capsule Compiler
#include "capsule/testdata/generator_smoke_test.out.h"

namespace test_ns {

size_t SubCapsuleM::ComputeStorageSize() const {
  ::capsule::SizeBuilder sb;
  sb.Add(sub_id);
  return sb.Build();
}

size_t FullFeatureM::ComputeStorageSize() const {
  ::capsule::SizeBuilder sb;
  sb.Add(id);
  sb.Add(code);
  sb.Add(enabled);
  sb.Add(name);
  sb.Add(items);
  sb.Add(nested);
  sb.Add(count);
  sb.Add(old_field);
  return sb.Build();
}

size_t SubCapsuleM::Encode(::capsule::Encoder* e) const {
  e->Add(sub_id_FieldHash, sub_id);
}

size_t FullFeatureM::Encode(::capsule::Encoder* e) const {
  e->Add(id_FieldHash, id);
  e->Add(code_FieldHash, code);
  e->Add(enabled_FieldHash, enabled);
  e->Add(name_FieldHash, name);
  e->Add(items_FieldHash, items);
  e->Add(nested_FieldHash, nested);
  e->Add(count_FieldHash, count);
  e->Add(old_field_FieldHash, old_field);
}

::core::Result SubCapsuleM::Decode(::capsule::Decoder* d) const {
  has_.resize(kFieldCount, false);
  ::core::Code ret = ::core::Code::kOk;
  ret.Incorporate(d->Find<decltype(sub_id)>(sub_id_FieldHash, &sub_id, sub_id_Default, has_[sub_id_Index]));
  return ret;
}

::core::Result SubCapsuleV::Decode(::capsule::Decoder* d) const {
  has_.resize(kFieldCount, false);
  ::core::Code ret = ::core::Code::kOk;
  ret.Incorporate(d->Find<decltype(sub_id)>(sub_id_FieldHash, &sub_id, sub_id_Default, has_[sub_id_Index]));
  return ret;
}

::core::Result FullFeatureM::Decode(::capsule::Decoder* d) const {
  has_.resize(kFieldCount, false);
  ::core::Code ret = ::core::Code::kOk;
  ret.Incorporate(d->Find<decltype(id)>(id_FieldHash, &id, id_Default, has_[id_Index]));
  ret.Incorporate(d->Find<decltype(code)>(code_FieldHash, &code, code_Default, has_[code_Index]));
  ret.Incorporate(d->FindCapsule(enabled_FieldHash, &enabled, enabled_Default, has_[enabled_Index]));
  ret.Incorporate(d->Find<decltype(name)>(name_FieldHash, &name, name_Default, has_[name_Index]));
  ret.Incorporate(d->FindStringVector(items_FieldHash, &items, has_[items_Index]));
  ret.Incorporate(d->FindCapsule(nested_FieldHash, &nested, nested_Default, has_[nested_Index]));
  ret.Incorporate(d->Find<decltype(count)>(count_FieldHash, &count, count_Default, has_[count_Index]));
  ret.Incorporate(d->Find<decltype(old_field)>(old_field_FieldHash, &old_field, old_field_Default, has_[old_field_Index]));
  return ret;
}

::core::Result FullFeatureV::Decode(::capsule::Decoder* d) const {
  has_.resize(kFieldCount, false);
  ::core::Code ret = ::core::Code::kOk;
  ret.Incorporate(d->Find<decltype(id)>(id_FieldHash, &id, id_Default, has_[id_Index]));
  ret.Incorporate(d->Find<decltype(code)>(code_FieldHash, &code, code_Default, has_[code_Index]));
  ret.Incorporate(d->FindCapsule(enabled_FieldHash, &enabled, enabled_Default, has_[enabled_Index]));
  ret.Incorporate(d->Find<decltype(name)>(name_FieldHash, &name, name_Default, has_[name_Index]));
  ret.Incorporate(d->FindStringVector(items_FieldHash, &items, has_[items_Index]));
  ret.Incorporate(d->FindCapsule(nested_FieldHash, &nested, nested_Default, has_[nested_Index]));
  ret.Incorporate(d->Find<decltype(count)>(count_FieldHash, &count, count_Default, has_[count_Index]));
  ret.Incorporate(d->Find<decltype(old_field)>(old_field_FieldHash, &old_field, old_field_Default, has_[old_field_Index]));
  return ret;
}

}  // namespace test_ns
