
cc_binary(
  name = "empty_main",
  srcs = ["empty_main.cc"],
)

cc_test(
  name = "empty_test",
  deps = [":basic_test",],
  srcs = ["empty_test.cc"],
)

cc_library(
  name = "basic_test",
  hdrs = ["basic_test.h"],
  srcs = ["basic_test.cc"],
)
